feat(orm): add typeorm, add sessions db store
opengovsg/ts-template pull request #1625
Opened 2022-08-04 02:26 UTC by njenwei

## Context

- Replace `sequelize` with `typeorm`
  - Added migration commands, `migration:run` and `migration:gen` and updated Readme
  - Added initial migration
  - Added seed placeholder
  - Renamed `models` to `entities`
- Add nestjs sessions DB store to persist across reloads
  - New `Session` typeorm entity
- Updated frontend dashboard to a snazzier look.

2022-08-04 08:02 UTC, LoneRifle requested changes
lgtm otherwise

2022-08-04 08:02 UTC, LoneRifle commented on backend/src/database/seeds/seed.ts
> +void main()
HAS uses seed scripts that make use of typeorm migrations. Would you consider this approach?

2022-08-04 08:02 UTC, LoneRifle commented on backend/src/auth/auth.service.ts
> +      from: `Starter Kit <${this.config.get('otp.email')}>`,
?

2022-08-05 02:00 UTC, njenwei commented on backend/src/auth/auth.controller.ts
> +import { pick } from 'lodash'
Removed

2022-08-05 02:06 UTC, njenwei commented on backend/src/database/seeds/seed.ts
> +void main()
Yes, such a good idea!

2022-08-05 02:10 UTC, njenwei commented on backend/src/auth/auth.service.ts
> +      from: `Starter Kit <${this.config.get('otp.email')}>`,
Felt like this didn't deserve a spot in the config file and make it longer than it should be

2022-08-05 04:50 UTC, LoneRifle commented on backend/src/auth/auth.service.ts
> +      from: `Starter Kit <${this.config.get('otp.email')}>`,
I think that's okay - people may want to avoid perturbing the codebase especially for one-liners like these, so am okay that this is something that takes up space in config file. Has an added bonus of implying to the reader what product the config file is for.

2022-08-05 04:56 UTC, LoneRifle approved these changes

2022-08-05 13:01 UTC, njenwei commented on backend/src/auth/auth.service.ts
> +      from: `Starter Kit <${this.config.get('otp.email')}>`,
👍

2022-08-05 14:31 UTC, merged